<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>71e7a278-9626-495c-9940-c853a4695d8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mhi2nd']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://rdsig.yahoo.co.jp/_ylt=A2Ri8cS.F3FdlGUANp.JBtF7/RV=2/RE=1567779134/RH=cmRzaWcueWFob28uY28uanA-/RB=bMyuR7aDvOj9diVg.FEJmvEfVxY-/RU=aHR0cHM6Ly9hdWN0aW9ucy55YWhvby5jby5qcC8A/RK=0/RS=gLfo7M8gTN0sCgXTZKcgKHBtugw-</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ヤフオク!</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mhi2nd&quot;)/a[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='mhi2nd']/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ヤフオク!')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='トラベル'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ショッピング'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='プレミアム'])[1]/preceding::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://rdsig.yahoo.co.jp/_ylt=A2Ri8cS.F3FdlGUANp.JBtF7/RV=2/RE=1567779134/RH=cmRzaWcueWFob28uY28uanA-/RB=bMyuR7aDvOj9diVg.FEJmvEfVxY-/RU=aHR0cHM6Ly9hdWN0aW9ucy55YWhvby5jby5qcC8A/RK=0/RS=gLfo7M8gTN0sCgXTZKcgKHBtugw-')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://rdsig.yahoo.co.jp/_ylt=A3aX6e4Q5nBdMmkATXiJBtF7/RV=2/RE=1567766416/RH=cmRzaWcueWFob28uY28uanA-/RB=xptQSR5VMYCb5mJP5srjOLXDwqA-/RU=aHR0cHM6Ly9hdWN0aW9ucy55YWhvby5jby5qcC8A/RK=0/RS=IaJnaTblR47mqyIs67N0aZRXmF4-')]</value>
   </webElementXpaths>
</WebElementEntity>
